/** Build-time only: reuse identical registry metadata without bundling a second copy. */
export function generateCapabilityCatalog(
  entries: readonly object[],
  groups: Record<string, Record<string, Record<string, unknown>>>
): string {
  const imports = new Map<string, string>();
  const keyLists = new Map<string, string>();
  const rows = entries.map((entry) => {
    const values = Object.entries(entry);
    const method = values.find(([key]) => key === 'method')?.[1] as unknown;
    const found =
      typeof method === 'string'
        ? Object.entries(groups).find(([, definitions]) => Object.hasOwn(definitions, method))
        : undefined;
    if (!found || typeof method !== 'string') return JSON.stringify(entry);
    const [group, definitions] = found;
    const definition = definitions[method];
    if (!definition) return JSON.stringify(entry);
    const shared = values
      .filter(
        ([key, value]) =>
          (value === null || typeof value !== 'object') &&
          Object.hasOwn(definition, key) &&
          JSON.stringify(value) === JSON.stringify(definition[key])
      )
      .map(([key]) => key);
    if (shared.length < 3) return JSON.stringify(entry);
    const keys = JSON.stringify(shared);
    const keyName = keyLists.get(keys) ?? `fields${keyLists.size}`;
    keyLists.set(keys, keyName);
    const symbol = `${group.toUpperCase().replaceAll('-', '_')}_CAPABILITY_DEFINITIONS`;
    imports.set(group, symbol);
    const rest = Object.fromEntries(values.filter(([key]) => !shared.includes(key)));
    return `{...metadata(${symbol}[${JSON.stringify(method)}],${keyName}),${JSON.stringify(rest).slice(1, -1)}}`;
  });
  return `// Generated by scripts/audit-alibaba-api.ts. Do not edit.
import type { ApiCapability } from '../types';
${[...imports].map(([group, symbol]) => `import { ${symbol} } from './${group}-capabilities';`).join('\n')}
${[...keyLists].map(([keys, name]) => `const ${name} = ${keys} as const;`).join('\n')}
function metadata<T extends object, K extends keyof T>(definition: T, keys: readonly K[]): Pick<T, K> {
  const result = {} as Pick<T, K>;
  for (const key of keys) result[key] = definition[key];
  return result;
}
export const API_CAPABILITIES = [${rows.join(',\n')}] as const satisfies readonly ApiCapability[];
`;
}
