/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env= --include-runtime=false apps/api/src/worker-configuration.d.ts` (hash: 64134377aecc13e3c6393280e9391483)
interface __BaseEnv_Env {
  DB: D1Database;
  ONE_VEGETABLE_API_PREFIX: '/api/v1';
  ONE_VEGETABLE_ENVIRONMENT: 'staging' | 'production' | 'self-hosted';
  ONE_VEGETABLE_GATEWAY_MODE: 'replay' | 'disabled' | 'real';
  ONE_VEGETABLE_CORS_ORIGINS?: 'https://staging.example.invalid' | 'https://app.example.invalid';
  ONE_VEGETABLE_MUTATION_FLAGS:
    | ''
    | 'operation:publishProduct,operation:saveProductDraft,operation:updateProduct,operation:updateProductDisplay,operation:operatePhotoGroup,operation:uploadPhoto,operation:transferPhotoFromUrl';
  ONE_VEGETABLE_REQUEST_RETENTION_DAYS: '30';
  ONE_VEGETABLE_AUTH_MODE: 'password' | 'passkey';
  BOOTSTRAP_ADMIN_TOKEN?: string;
  ONE_VEGETABLE_CREDENTIAL_ENCRYPTION_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface StagingEnv {
    DB: D1Database;
    ONE_VEGETABLE_API_PREFIX: '/api/v1';
    ONE_VEGETABLE_ENVIRONMENT: 'staging';
    ONE_VEGETABLE_GATEWAY_MODE: 'replay';
    ONE_VEGETABLE_CORS_ORIGINS: 'https://staging.example.invalid';
    ONE_VEGETABLE_MUTATION_FLAGS: '';
    ONE_VEGETABLE_REQUEST_RETENTION_DAYS: '30';
    ONE_VEGETABLE_AUTH_MODE: 'password';
  }
  interface ProductionEnv {
    DB: D1Database;
    ONE_VEGETABLE_API_PREFIX: '/api/v1';
    ONE_VEGETABLE_ENVIRONMENT: 'production';
    ONE_VEGETABLE_GATEWAY_MODE: 'disabled';
    ONE_VEGETABLE_CORS_ORIGINS: 'https://app.example.invalid';
    ONE_VEGETABLE_MUTATION_FLAGS: '';
    ONE_VEGETABLE_REQUEST_RETENTION_DAYS: '30';
    ONE_VEGETABLE_AUTH_MODE: 'password';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ONE_VEGETABLE_API_PREFIX'
      | 'ONE_VEGETABLE_ENVIRONMENT'
      | 'ONE_VEGETABLE_GATEWAY_MODE'
      | 'ONE_VEGETABLE_CORS_ORIGINS'
      | 'ONE_VEGETABLE_MUTATION_FLAGS'
      | 'ONE_VEGETABLE_REQUEST_RETENTION_DAYS'
      | 'ONE_VEGETABLE_AUTH_MODE'
      | 'BOOTSTRAP_ADMIN_TOKEN'
      | 'ONE_VEGETABLE_CREDENTIAL_ENCRYPTION_KEY'
    >
  > {}
}
