import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

interface MockDataSource {
  readonly fileName: string;
  readonly exportName: string;
  readonly typeName: string;
}

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'packages/core/src/generated/mock-data.ts');
const check = process.argv.includes('--check');
const sources: MockDataSource[] = [
  {
    fileName: 'product-description-templates.json',
    exportName: 'PRODUCT_DESCRIPTION_TEMPLATE_MOCK_DATA',
    typeName: 'ProductDescriptionTemplateMockData'
  },
  { fileName: 'products.json', exportName: 'PRODUCT_MOCK_DATA', typeName: 'ProductMockData' },
  { fileName: 'photos.json', exportName: 'PHOTO_MOCK_DATA', typeName: 'PhotoMockData' },
  { fileName: 'rfqs.json', exportName: 'RFQ_MOCK_DATA', typeName: 'RfqMockData' },
  { fileName: 'trades.json', exportName: 'TRADE_MOCK_DATA', typeName: 'TradeMockData' },
  {
    fileName: 'logistics.json',
    exportName: 'LOGISTICS_MOCK_DATA',
    typeName: 'LogisticsMockData'
  },
  { fileName: 'insights.json', exportName: 'INSIGHTS_MOCK_DATA', typeName: 'InsightsMockData' },
  { fileName: 'system.json', exportName: 'SYSTEM_MOCK_DATA', typeName: 'SystemMockData' }
];

const declarations: string[] = [];
for (const source of sources) {
  const raw = await readFile(resolve(root, 'mock/data', source.fileName), 'utf8');
  const value: unknown = JSON.parse(raw);
  declarations.push(
    `export const ${source.exportName}: ${source.typeName} = ${JSON.stringify(value, null, 2)};`
  );
}

const output = `// Generated by scripts/generate-mock-data.ts from mock/data. Do not edit.\nimport type { InsightsMockData, LogisticsMockData, PhotoMockData, ProductDescriptionTemplateMockData, ProductMockData, RfqMockData, SystemMockData, TradeMockData } from '../mock-data-contract';\n\n${declarations.join('\n\n')}\n`;

if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('Generated mock data is stale. Run pnpm generate:mock-data.');
  }
} else {
  await writeFile(target, output, 'utf8');
}
