import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

interface RootPackageManifest {
  version: string;
}

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'packages/core/src/version.ts');
const check = process.argv.includes('--check');
const manifest = await readManifest();
const output = `// Generated by scripts/generate-version.ts from package.json. Do not edit.\nexport const APP_VERSION = '${manifest.version}';\n`;

if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('Generated application version is stale. Run pnpm generate:version.');
  }
} else {
  await writeFile(target, output, 'utf8');
}

async function readManifest(): Promise<RootPackageManifest> {
  const value: unknown = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  if (!isRecord(value) || typeof value.version !== 'string') {
    throw new Error('Root package.json must contain a string version.');
  }
  return { version: value.version };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
