import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { format } from 'prettier';

import { readAccountVerificationSnapshot } from './lib/account-verification';

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'packages/core/src/generated/account-verification.ts');
const check = process.argv.includes('--check');
const snapshot = await readAccountVerificationSnapshot(root);
const output = await format(
  `// Generated by scripts/generate-account-verification.ts from the sanitized account verification snapshot. Do not edit.
export const ACCOUNT_VERIFICATION_SNAPSHOT = ${JSON.stringify(snapshot, null, 2)} as const;
`,
  { parser: 'typescript', singleQuote: true, trailingComma: 'none', printWidth: 100 }
);

if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error(
      'Generated account verification snapshot is stale. Run pnpm generate:account-verification.'
    );
  }
} else {
  await writeFile(target, output, 'utf8');
}
