import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

interface MockDataSource {
  readonly fileName: string;
  readonly exportName: string;
  readonly typeName: string;
}

const root = resolve(import.meta.dirname, '..');
const mockDataRoot = resolve(root, 'mock/data');
const mockAssetMarker = 'mock-asset:';
const mockAssetFileName = /^[a-z0-9][a-z0-9-]*\.svg$/u;
const target = resolve(root, 'packages/core/src/generated/mock-data.ts');
const templateTarget = resolve(root, 'packages/core/src/generated/product-description-templates.ts');
const check = process.argv.includes('--check');
const sources: MockDataSource[] = [
  { fileName: 'products.json', exportName: 'PRODUCT_MOCK_DATA', typeName: 'ProductMockData' },
  { fileName: 'photos.json', exportName: 'PHOTO_MOCK_DATA', typeName: 'PhotoMockData' },
  { fileName: 'rfqs.json', exportName: 'RFQ_MOCK_DATA', typeName: 'RfqMockData' },
  { fileName: 'trades.json', exportName: 'TRADE_MOCK_DATA', typeName: 'TradeMockData' },
  {
    fileName: 'logistics.json',
    exportName: 'LOGISTICS_MOCK_DATA',
    typeName: 'LogisticsMockData'
  },
  { fileName: 'insights.json', exportName: 'INSIGHTS_MOCK_DATA', typeName: 'InsightsMockData' },
  { fileName: 'system.json', exportName: 'SYSTEM_MOCK_DATA', typeName: 'SystemMockData' }
];

const declarations: string[] = [];
for (const source of sources) {
  const raw = await readFile(resolve(mockDataRoot, source.fileName), 'utf8');
  const value = await hydrateMockAssets(JSON.parse(raw) as unknown);
  declarations.push(
    `export const ${source.exportName}: ${source.typeName} = ${JSON.stringify(value, null, 2)};`
  );
}

const output = `// Generated by scripts/generate-mock-data.ts from mock/data. Do not edit.\nimport type { InsightsMockData, LogisticsMockData, PhotoMockData, ProductMockData, RfqMockData, SystemMockData, TradeMockData } from '../mock-data-contract';\n\n${declarations.join('\n\n')}\n`;
const templateValue: unknown = JSON.parse(
  await readFile(resolve(mockDataRoot, 'product-description-templates.json'), 'utf8')
);
const templateOutput = `// Generated by scripts/generate-mock-data.ts from the curated bundled templates. Do not edit.\nimport type { BundledProductDescriptionTemplateData } from '../mock-data-contract';\n\nexport const BUNDLED_PRODUCT_DESCRIPTION_TEMPLATE_DATA: BundledProductDescriptionTemplateData = ${JSON.stringify(templateValue, null, 2)};\n`;

if (check) {
  const [current, currentTemplates] = await Promise.all([
    readFile(target, 'utf8').catch(() => ''),
    readFile(templateTarget, 'utf8').catch(() => '')
  ]);
  if (current !== output || currentTemplates !== templateOutput) {
    throw new Error('Generated mock data is stale. Run pnpm generate:mock-data.');
  }
} else {
  await Promise.all([writeFile(target, output, 'utf8'), writeFile(templateTarget, templateOutput, 'utf8')]);
}

async function hydrateMockAssets(value: unknown): Promise<unknown> {
  if (typeof value === 'string' && value.startsWith(mockAssetMarker)) {
    const fileName = value.slice(mockAssetMarker.length);
    if (!mockAssetFileName.test(fileName)) {
      throw new Error(`Invalid mock asset reference: ${value}`);
    }
    const contents = await readFile(resolve(mockDataRoot, 'assets', fileName));
    return `data:image/svg+xml;base64,${contents.toString('base64')}`;
  }
  if (Array.isArray(value)) return Promise.all(value.map((item) => hydrateMockAssets(item)));
  if (value !== null && typeof value === 'object') {
    const entries = await Promise.all(
      Object.entries(value).map(async ([key, item]) => [key, await hydrateMockAssets(item)] as const)
    );
    return Object.fromEntries(entries);
  }
  return value;
}
