import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { format } from 'prettier';

import { parseReleaseNotesDocument } from './lib/release-notes';

interface RootPackageManifest {
  version: string;
}

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'packages/core/src/generated/release-notes.ts');
const check = process.argv.includes('--check');
const document = parseReleaseNotesDocument(
  JSON.parse(await readFile(resolve(root, 'release-notes/releases.json'), 'utf8')) as unknown
);
const manifest = await readManifest();
if (!document.releases.some((release) => release.version === manifest.version)) {
  throw new Error(`Release notes must contain the current workspace version ${manifest.version}.`);
}

const output = await format(
  `// Generated by scripts/generate-release-notes.ts from release-notes/releases.json. Do not edit.
export const RELEASE_NOTES_DOCUMENT = ${JSON.stringify(document, null, 2)} as const;
`,
  { parser: 'typescript', singleQuote: true, trailingComma: 'none', printWidth: 100 }
);

if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== output) {
    throw new Error('Generated release notes are stale. Run pnpm generate:release-notes.');
  }
} else {
  await writeFile(target, output, 'utf8');
}

async function readManifest(): Promise<RootPackageManifest> {
  const value: unknown = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  if (!isRecord(value) || typeof value.version !== 'string') {
    throw new Error('Root package.json must contain a string version.');
  }
  return { version: value.version };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
